version: '3.8'
services:
  cdpinnova-app:
    image: registry.key-biz.cloud/cl/entando/cdp/innova/cdp-innova-cognistreamer-connector/cdpinnova:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cdpinnova-postgresql:5432/innova2_ds_db
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://cdpinnova-postgresql:5432/innova2_ds_db
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
#      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
